#!perl -w
use strict;
use Net::SMTP;
use MIME::Lite;

my $log_dir = "/opt/robots-checker/logs";

my ($sec, $min, $hr, $day, $mon, $year) = localtime;

my $timestamp = sprintf("%02d_%02d_%04d_%02d_%02d_%02d\n", $day, $mon + 1, 1900 + $year, $hr, $min, $sec);

my $log_file = "$log_dir/mongoose.log.$timestamp.html";

$log_file =~ s/\s+//g;
$log_file =~ s/\\/_/g;

print "Running : /usr/local/bin/cucumber -f html > $log_file\n";

my $return_val = `/usr/local/bin/cucumber -f html` ;

my $re='(\d+) scenarious .*?(\d+).*?(\d+).*?(\d+)';
my $summary = "Could not fetch summary";

if ($return_val =~ m/$re/isg)
{
    my $int1=$1;
    my $int2=$2;
    my $int3=$3;
    my $int4=$4;
    print "($int1) ($int2) ($int3) ($int4) \n";
    $summary = "$int1 Scenarios\n$int2 passed\n$int3 Steps\n$int4 passed.";
}

print "Summary: $summary\n";

# print "Return val : $return_val" ;

$return_val =~ s/<title>Cucumber<\/title>/<title>Timescity Mongoose ($timestamp)<\/title>/;

$return_val =~ s/<h1>Cucumber Features<\/h1>/<h1>Timescity Mongoose<\/h1>/;

open (LOG, "> $log_file") || die "Could not open log file for writing : $!";
print LOG $return_val;
close LOG;

# now zip the file

`gzip $log_file`;

# $log_file =~ s/\//\\\//g;


## =========
    # Set the fields required by Mailer...
    # ... and send it
    # Header
my    $msg = MIME::Lite->new(
                            From    => 'pradeep.sethi@indiatimes.co.in',
                            To      => 'pradeep.sethi@indiatimes.co.in',
                            Subject => 'Mongoose output : ' . $timestamp,
                            Type    =>'multipart/mixed',
                            Debug   => 1
			   );
    # Body Content
    $msg->attach(
                Type     => 'TEXT',
                Data     => $summary
		 );
    # Attachment
    $msg->attach(
                Type     => 'application/zip',
                Path     => "$log_file.gz",
                Filename => "mongoose_report_compressed.html.gz",
                Disposition => 'attachment'
		 );

MIME::Lite->send ('smtp', 'cmailer.indiatimes.com');
$msg->send;


